### PR TITLE
Doc Update

### PR DESCRIPTION
**Pull request by 4DRIAN0RTIZ**
Update doc for mapping using modifiers.

### CODE REVIEW

**Comment by 4DRIAN0RTIZ** [comment]
Thank you very much for the response! 🙏 The PR was created with the idea of helping people like me who were unaware of that feature in Neovim/Vim. 🧑‍💻✨ I believe having that information on the main page of the repository 📄 could be helpful.

But I'd be happy to assist with the section you mentioned! 😊📚

**Comment by nanotee** [comment]
Done! The wiki page is located at https://github.com/nanotee/sqls.nvim/wiki/Tips-and-tricks

**Comment by 4DRIAN0RTIZ** [comment]
Ready! 😄 

I thank you very much.

If you wish you can close the pr ✌🏼

**Comment by nanotee** [comment]
Thank you for contributing! Much appreciated

**Pull request closed without merging**
